/*
=========================================================
Project : Inventory & Supply Chain SQL Analysis
File    : 07_analyst_challenges.sql
Author  : Nusrat Jahan Kashfia
Database: MySQL 8
=========================================================
*/

/*
=========================================================
Analyst-Level Challenges
=========================================================
*/

/*
1. Calculate inventory value for every product
*/
SELECT
    p.product_id,
    p.product_name,
    i.stock_on_hand,
    p.unit_cost,
    (i.stock_on_hand * p.unit_cost) AS inventory_value
FROM products p
JOIN inventory i
    ON p.product_id = i.product_id;

/*
2. Find the top 10 products by inventory value
*/
SELECT
    p.product_name,
    SUM(i.stock_on_hand * p.unit_cost) AS inventory_value
FROM inventory i
JOIN products p
    ON i.product_id = p.product_id
GROUP BY p.product_name
ORDER BY inventory_value DESC
LIMIT 0, 10;

/*
3. Find the bottom 10 products by inventory value
*/
SELECT
    p.product_name,
    SUM(i.stock_on_hand * p.unit_cost) AS inventory_value
FROM inventory i
JOIN products p
    ON i.product_id = p.product_id
GROUP BY p.product_name
ORDER BY inventory_value ASC
LIMIT 0, 10;


/*
4. Identify slow-moving products
   High stock and low sales
*/
SELECT
    p.product_name,
    SUM(i.stock_on_hand) AS stock,
    SUM(s.quantity_sold) AS sales
FROM inventory i
JOIN products p
    ON i.product_id = p.product_id
JOIN sales s
    ON i.product_id = s.product_id
GROUP BY p.product_name
HAVING stock > 100
ORDER BY sales ASC;

/*
5. Identify fast-moving products
   High sales and low stock
*/
SELECT
    p.product_name,
    SUM(i.stock_on_hand) AS stock,
    SUM(s.quantity_sold) AS sales
FROM inventory i
JOIN products p
    ON i.product_id = p.product_id
JOIN sales s
    ON i.product_id = s.product_id
GROUP BY p.product_name
HAVING stock < 100
ORDER BY sales DESC;

/*
6. Calculate total revenue generated by each product
*/
SELECT
    p.product_name,
    SUM(s.revenue) AS revenue_generate
FROM sales s
JOIN products p
    ON s.product_id = p.product_id
GROUP BY p.product_name;

/*
7. Calculate average monthly sales by product
*/
SELECT
    product_id,
    MONTH(sale_date) AS month,
    SUM(revenue) AS monthly_sales
FROM sales
GROUP BY
    product_id,
    MONTH(sale_date)
ORDER BY month;

/*
8. Calculate inventory turnover for each product
*/
SELECT
    p.product_name,
    SUM(s.quantity_sold) /
    ((MAX(i.stock_on_hand) + MIN(i.stock_on_hand)) / 2) AS inventory_turnover
FROM products p
JOIN sales s
    ON p.product_id = s.product_id
JOIN inventory i
    ON p.product_id = i.product_id
GROUP BY p.product_name;

/*
9. Rank products by sales revenue
*/
SELECT
    p.product_name,
    SUM(s.revenue) AS total_inventory
FROM products p
JOIN sales s
    ON p.product_id = s.product_id
GROUP BY p.product_name
ORDER BY total_inventory DESC;

/*
10. Rank suppliers by total purchasing spend
*/
SELECT
    po.supplier_name,
    SUM(po.purchase_cost) AS total_purchase_spend
FROM purchase_orders po
GROUP BY po.supplier_name
ORDER BY total_purchase_spend DESC;